names = {
    'lm_0':  'naso',
    'lm_1':  'occhio_sx_interno',
    'lm_2':  'occhio_sx_esterno',
    'lm_3':  'orecchio_sx',
    'lm_4':  'occhio_dx_esterno',
    'lm_5':  'occhio_dx_interno',
    'lm_6':  'orecchio_dx',
    'lm_7':  'bocca_sopra',
    'lm_8':  'bocca_sotto',
    'lm_9':  'spalla_sx',
    'lm_10': 'gomito_sx',
    'lm_11': 'polso_sx',
    'lm_12': 'spalla_dx',
    'lm_13': 'gomito_dx',
    'lm_14': 'polso_dx',
    'lm_15': 'mano_sx',
    'lm_16': 'mano_dx',
    'lm_17': 'anca_sx',
    'lm_18': 'ginocchio_sx',
    'lm_19': 'caviglia_sx',
    'lm_20': 'anca_dx',
    'lm_21': 'ginocchio_dx',
    'lm_22': 'caviglia_dx',
    'lm_23': 'orecchio_sx_superiore',
    'lm_24': 'orecchio_dx_superiore',
    'lm_25': 'spina_dorsale_inferiore',
    'lm_26': 'spina_dorsale_superiore',
    'lm_27': 'collo',
    'lm_28': 'radice_coda',
    'lm_29': 'ginocchio_sx_interno',
    'lm_30': 'ginocchio_dx_interno',
    'lm_31': 'caviglia_sx_interno',
    'lm_32': 'caviglia_dx_interno',
}

# Stereotypy labels (example)
labels_FG4 = [{'stereotypy': 8, 'text': 'agita mani in aria', 'start': 0.00, 'end': 4.00},
                   {'stereotypy': 8, 'text': 'agita mani in aria', 'start': 5.50, 'end': 9.50},
                   {'stereotypy': 8, 'text': 'agita mani in aria', 'start': 13.70, 'end': 14.20},
                   {'stereotypy': 8, 'text': 'agita mani in aria', 'start': 17.00, 'end': 26.00},
                   {'stereotypy': 1, 'text': 'dondola busto', 'start': 10.80, 'end': 12.00}]